export const collateralTypeData = {
    label: '抵质押物类型',
    isCollapsed: false,
    code: 'type',
    sliceKey: 10,
    list: [
        { label: '全部', value: '' },
        { label: '住宅', value: 1 },
        { label: '商业', value: 2 },
        { label: '办公楼', value: 3 },
        { label: '工业房地产', value: 4 },
        { label: '光地（工业）', value: 5 },
        { label: '光地（商业）', value: 6 },
        { label: '光地（商住）', value: 7 },
        { label: '光地（住宅）', value: 8 },
        { label: '在建工程', value: 9 },
        { label: '机器设备', value: 10 },
        { label: '生产设备', value: 11 },
        { label: '运输设备', value: 12 },
        { label: '林权', value: 13 },
        { label: '海域使用权', value: 14 },
        { label: '船舶', value: 15 },
        { label: '其他', value: 16 },
        { label: '产品、材料等', value: 17 },
        { label: '大宗物资', value: 18 },
        { label: '工业品、家电等', value: 19 },
        { label: '粮食物资', value: 20 },
    ],
};
